### ISSUE TITLE
Items mistakenly shown as used

### ISSUE THREAD

**Issue by latteier** [jendrikseipp/vulture#103]
Vulture looks great! I'm evaluating it to use on a large code base.

One issue I'm running into is that because `_get_unused_items` looks items up by name, if I have one module with a used function `foo` and another module with an unused function `foo`, the unused `foo` won't be reported as unused, since when looking in the list of used names it will be found.

I would guess that the fix would be to be prefixed by package/module.

**Comment by RJ722** [comment]
Hi @latteier!

> I would guess that the fix would be to be prefixed by package/module.

That would actually be hard to implement because of how ast's work. Also, even if implemented, it would break "whitelisting" - where we create another package containing the pseudo dead code.

To overcome this problem for now, may be, you can run this on individual files and then on the whole codebase - and thereafter examine the results.

Let us know if we can help! 😄

**Comment by latteier** [comment]
Thanks for the quick response! I've been thinking about the issue some more and agree that it would be tricky to implement.

It seems like finding unused code within the context of a single file is the most reliable mode of operation. However for the codebase I'm working with it would be useful to know whether seemingly unused names are imported and used elsewhere. I'll think more about how to test for that.

**Comment by RJ722** [comment]
So, can we close this issue?

**Comment by jendrikseipp** [comment]
I think we can :-)
