### ISSUE TITLE
Support for nolint-like comments

### ISSUE THREAD

**Issue by szborows** [jendrikseipp/vulture#107]
Sometimes function is not used, but it is on purpose. Example: could be Celery workers' tasks.

There should be a way to mark functions as intentionally non-referenced.

Proposal:
`# vulture-ignore: unused-function`

**Comment by RJ722** [comment]
HI @szborows!

You can add a whitelist file and add a variable named exactly the same way as the unused function!

Comments reduce the readability of the code.

**Comment by szborows** [comment]
I respect your POV but I disagree with it. Here's why:

- this separate file is like configuration file. Zero-conf tools are more attractive and easier to both execute and start with
- easier refactor: It's easier to change single place than two (e.g. function name). With Celery it's even more important, because function name is usually also a task name
- coupling: it's better when things are nearby each other

I agree that comments reduce readability, but there's no other known mechanism that is coupled with function/statement, doesn't influence generated code and could be used by 3rd-party tool like vulture.

**Comment by jendrikseipp** [comment]
I agree that it would be nice if we didn't need an extra whitelist file, but altogether I believe inline nolint comments have more drawbacks than advantages:

* Code is cluttered by nolint comments
* No easy way to see all dead code (whitelist file provides such a list)
* Additional code for this feature would be needed (whitelist does not need special code)

The fact that both the code and the whitelist have to be edited during refactoring is not so bad since it is easy to test that the whitelist is still up to date by running `python whitelist.py`.
