### ISSUE TITLE
Use the logging module

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#108]
Currently, vulture uses the naive way of managing the logs by directly saving them as strings and printing them to `stdout` whenever in verbose mode. An alternative way of managing logs is through the python's [logging module](https://docs.python.org/3.5/library/logging.html).

**Comment by jendrikseipp** [comment]
I agree that the logging module seems like an obvious choice, but I see no real advantage using it. If you see one, feel free to reopen :-)

**Comment by jayvdb** [comment]
Note the following isnt a definitive reason for using logging ; I'm only suggesting this is one possible use-case which might justify the additional work/complexity.  Maybe it might also spark other ideas.

As coala uses vulture as an import instead of cli, the `logging` system processes these messages in a much more reliable manner than them appearing on stdout, especially relevant for multi-threaded/-processing environments like coala and pytest.  I must admit that coala does pipe the vulture stdout to a buffer, and it will be routed to the user via `logging` anyway, and I'm not sure off-hand when we show it to the user : probably only on errors, especially errors & failures in our tests.  coala has only recently switched over its codebase to using `logging`, so I am fairly confident it doesnt yet have additional features for linters that are also using `logging`.  But that is likely also because we dont have many linters which use `logging`, so havent had reason to improve that area.

**Comment by jendrikseipp** [comment]
I think Vulture currently makes three different types of output:

* Vulture.report() reports unused code. This should probably keep printing to stdout.
* There are several error messages printed to stderr. These could be changed to logging.error, but should still land on stderr.
* Vulture._log() prints debugging info. This could use logging.debug, I guess.

We also would have to make sure that using the logging module doesn't slow down Vulture (evaluating whether to print debugging info was a bottleneck in an earlier version). If you like, feel free to prepare a pull request :-)
