### ISSUE TITLE
False positive II

### ISSUE THREAD

**Issue by walles** [jendrikseipp/vulture#148]
```python
class HttpException(Exception):

    def __init__(self, url, status_code, text=""):
        self.url = url
        self.status_code = status_code
        self.text = text
        super(HttpException, self).__init__("Got status code %d on %s body %s"
                                            % (status_code, url, text))
```

Output with Vulture 0.29:
```
repro.py:4: unused attribute 'url' (60% confidence)
repro.py:5: unused attribute 'status_code' (60% confidence)
repro.py:6: unused attribute 'text' (60% confidence)
```

Expected output:
None

All the reported variables are used on the last line.

**Comment by walles** [comment]
Or on second thought, is it referring to the `self.` ones?

In that case, maybe refer to the unused variables as `self.url` or `HttpException.url` in the error message?

**Comment by RJ722** [comment]
> Or on second thought, is it referring to the self. ones?

Yups! 

> In that case, maybe refer to the unused variables as self.url or HttpException.url in the error message?

Actually, we report them as unused "attributes" rather than variables. But yeah, reporting with the object name prepended might be useful.

**Comment by jendrikseipp** [comment]
Since Vulture ignores scopes we can only report `self.url`, but not `HttpException.url`. If we implement this, we need to keep in mind that attributes can be nested, so for `foo.bar.baz` all three parts should be reported. This will make the code more complicated though and I don't think this is worth the effort since the messages already explain what's unused.
