### ISSUE TITLE
Enhancement: Making vulture a flake8 plugin

### ISSUE THREAD

**Issue by pykong** [jendrikseipp/vulture#161]
I believe `vulture` would make a useful addition to the flake8 plugin ecosystem, as finding dead code as part of the usual lining process would be great.

information on flake8 plugin development:
https://flake8.pycqa.org/en/latest/plugin-development/

**Comment by RJ722** [comment]
Hi @pykong,

This seems like a really nice idea, Thanks!

Let's see what @jendrikseipp has to say about this and in the end if we decide to get on with it, I think that I would be up for development as I shall be available for a month or so during late August.

**Comment by jendrikseipp** [comment]
I agree, that's a nice idea! @RJ722, it would be great if you found the time to work on this! I think https://github.com/PyCQA/flake8-docstrings should serve as a good example.

**Comment by pykong** [comment]
@RJ722 @jendrikseipp Great to see your enthusiasm.
I am usually very short on time myself but you can count me in if you need help with the development.

Keep in mind `vulture` is vital for any serious python dev because it fulfils an important code quality check no other tool (AFAIK) provides.

**Comment by onlinejudge95** [comment]
@RJ722 Happy to look into the issue. I would be making contact for contextual info.

**Comment by jendrikseipp** [comment]
Perfect, please coordinate with @RJ722.

**Comment by RJ722** [comment]
Hi everyone, I tried taking a stab at it yesterday (Merry Christmas to you too! :D) - But, it turns out that because of the way flake8 plugin works, a new instance of the plugin class is created for every new file, and it receives the filename/AST of only that file - due to which it isn't directly possible to report code used across different files.

Off the top of my head, I can think of two possible workarounds:
- For ever file, parse it's parent directory and run Vulture on the whole directory. Store the directory path in a set shared across different instances. This might work well for most of the cases, but if there is a more complex hierarchy, this is bound to fail.
- Ask users explicitly the paths they want to run Vulture on.

Did I miss something? Is there anything else we can do?

Also, I decided to call it `fluture`. Too punny?

**Comment by pykong** [comment]
@RJ722 Thanks for putting up the effort.
Regarding naming. I suggest to just call it it `flake8-vulture`.
This is simple and explicit, follows the naming scheme of other plugins (e.g. `flake8-mypy`) and does not hide the incorporation of `vulture`.

**Comment by RJ722** [comment]
@pykong I agree. thanks for your input!

**Comment by jendrikseipp** [comment]
Thanks for looking into this! Regarding the functionality, I think it's best to ask the flake8 devs how best to accumulate results over multiple files. Regarding the name, I agree that flake8-vulture sounds best.

**Comment by RJ722** [comment]
Thanks @jendrikseipp! I've opened https://gitlab.com/pycqa/flake8/issues/603

**Comment by pykong** [comment]
@RJ722 the maintainer of flake8 over there at GitLab does not seems to be too keen on `flake8-vulture`. Do not mind the heat he's given you. We all agreed on this thread that `vulture` would make a great addition to the flake8 ecosystem. 

Now we have to see whether it can actually be made to work. Technically it seems flake8 does not offer the functionality we require to do sojudged from aso's response on GitLab. That would be sad though.

**Comment by jendrikseipp** [comment]
I don't think it's worth fighting an uphill battle. If flake8 and vulture don't fit together, there's no need to try to work around that fact. I think our time is spent better on other usage issues like #160 and #164 .
