### ISSUE TITLE
Support loading options from a configuration file (pyproject.toml?)

### ISSUE THREAD

**Issue by Varriount** [jendrikseipp/vulture#164]
It would be nice if vulture supported using setup.cfg/setup.ini to retrieve whitelists, exclusions, etc. from.

**Comment by RJ722** [comment]
Hi @Varriount,

Thanks for the feedback, but I'm not sure that I entirely get what you're trying to say. Can you please give an example of what exactly are you asking for, please?

**Comment by tarkatronic** [comment]
Alternatively, perhaps `pyproject.toml` support would be good, as this is becoming The Way for configuration in the Python world. An example entry for `vulture` might look like:
```toml
[tool.vulture]
min-confidence = 70
exclude = ".eggs,.git,.*cache,.tox,.venv,build,dist"
```
This would allow a user to have more determinism in their `vulture` runs, since they would not have to specify command line options every time.

I recently implemented this in [tartufo](https://github.com/godaddy/tartufo/blob/ac18f615f0c2f7ae59813790cefcbce4214d7958/tartufo/config.py#L24..L51), based heavily on the work in [black](https://github.com/psf/black/blob/de6f4b1f6bd3211e80bc5a5f1f88e6ef69a550aa/black.py#L216..L249).

This style of configuration is being adopted in many other large Python tools. A list of other tools can be found here: https://github.com/flying-sheep/awesome-python-packaging

In addition, [mypy](https://github.com/python/mypy/issues/5205) will be adding support as well.

**Comment by jendrikseipp** [comment]
@tarkatronic sounds interesting! It would be awesome if you could make a pull request.

**Comment by RJ722** [comment]
@jendrikseipp I can work on this. However, adding support for `pyproject.toml` would mean having an external dependency `toml`. Are you okay with it?

**Comment by jendrikseipp** [comment]
Good point. I'm not sure. Having no external dependencies certainly has appeal. Also, it's not clear which TOML library we should use (there are 3 Python TOML libraries). Maybe we should defer this issue until the dust has settled on how to declare options for linters and similar tools.

**Comment by jendrikseipp** [comment]
I guess we could make the TOML dependency optional like isort does. Still, it's not clear which TOML library to use.

**Comment by RJ722** [comment]
https://pypi.org/project/toml/ seems to be the standard and most popular (more than 18k users according to https://github.com/uiri/toml)

**Comment by jendrikseipp** [comment]
I checked which projects use which toml library:
* toml: black, isort, mypy (WIP)
* tomlkit: poetry

So it seems "toml" is indeed the way to go. Especially, since we only need to load TOML, not modify it.

**Comment by jendrikseipp** [comment]
isort now bundles a vendorized copy of toml. We could probably do the same.

**Comment by exhuma** [comment]
Having some configuration support would be helpful for CI pipelines as well. Until recently I have been in the camp being "against yet another dependency" just for project development support like TOML. But a recent episode on a podcast changed my mind about this... let me find it back... [here it is](https://testandcode.com/119).

I would be willing to work on this if you let me know which way you'd like to go. I see either pyproject.toml with a vendored parser or a simple .ini file. I'm not all too opposed to adding a real dependency for a TOML parser instead of vendoring but I am leaning more towards vendoring too.

@jendrikseipp let me know if you want me to go ahead with one of those solutions.

**Comment by exhuma** [comment]
nb, this issue might benefit from a better subject. The primary topic is the be able to have config-values in a config file in addition to the cli-args. Might help others find it a bit better.

**Comment by jendrikseipp** [comment]
@exhuma thanks for the link! I'll listen to the episode and will get back to you on this.

**Comment by exhuma** [comment]
@jendrikseipp  I will likely start to dabble around with it tomorrow, just to familiarise myself with the project structure of `vulture` and `toml`. I don't mind if I need to rewrite that work as my main aim will be the aforementioned familiarisation 😉 If I'm happy with the result I'll open a PR, and you can go nutters with the review. I have a thick skin and am always fairly critical in reviews I do myself, so you don't need to worry about scaring me away 😉

**Comment by jendrikseipp** [comment]
@exhuma Sounds great! I listened to the podcast and think that the best solution is to add a dependency on `toml`. I recommend looking at how other projects use toml and pyproject.toml (e.g., black) to avoid reinventing the wheel :-)

**Comment by exhuma** [comment]
> I recommend looking at how other projects use toml and pyproject.toml (e.g., black) to avoid reinventing the wheel :-)

will do

**Comment by exhuma** [comment]
Done. Let me know what you thing :)

**Comment by RJ722** [comment]
Now that #215 has merged, let's close this?

**Comment by jendrikseipp** [comment]
Good point :-)
