### ISSUE TITLE
Can't ignore with # noqa

### ISSUE THREAD

**Issue by nameer** [jendrikseipp/vulture#205]
To understand the problem, here's a file `file.py`
```python
 import os  # noqa                 
 
 class Greeter:  # noqa: V102
     def greet(self):  # noqa: V103
         print("Hi")
```

As you can see, I have commented out the lines for vulture to ignore. Running `vulture file.py` is expected to pass. But this is still producing this error:

```
file.py:1: unused import 'os' (90% confidence)
file.py:4: unused class 'Greeter' (60% confidence)
file.py:5: unused function 'greet' (60% confidence)
```

**Comment by jendrikseipp** [comment]
The version that supports noqa has not been released yet. If you want to try it out, you'll have to install the latest version from the master branch. Be aware though that we will probably only support F401 and F841 in order to promote the use of whitelists instead of noqa (which litters the code with comments).

**Comment by CristhianMotoche** [comment]
Thanks for the clarification. @jendrikseipp

**Comment by nameer** [comment]
Thank you @jendrikseipp . When shall we expect the release?

**Comment by jendrikseipp** [comment]
> Thank you @jendrikseipp . When shall we expect the release?

F401 and F841 noqa comments are part of version 1.5.
