### ISSUE TITLE
Add support for TypedDict

### ISSUE THREAD

**Issue by ZeeD** [jendrikseipp/vulture#249]
snippet:
```python
from typing import TypedDict

class C(TypedDict):
    key: int

c: C = {'key': 0}
print(c['key'])
```
`vulture` says `unused variable 'key' (60% confidence)`, but shouldn't

**Comment by RJ722** [comment]
I agree that this should be done, but I'm not sure how complicated would it be. I'll take a look into it. A lot of things on my plate right now, so it will take some time.

**Comment by jendrikseipp** [comment]
I don't see an easy way to remove the false positive. Suggestions welcome :-)

**Comment by mariuswallraff** [comment]
No suggestion, but for other people landing here:  
A workaround is to use the function-call syntax like this:
`C = TypedDict("C", {"key": int})`

You can't use the nicer-looking keyword syntax, because then mypy is going to complain again. 🙂

**Comment by janosh** [comment]
You can also `noqa` all the attributes though [like the readme says](https://github.com/jendrikseipp/vulture#handling-false-positives), it ain't pretty:

```py
class ProcessResponse(TypedDict):
    timer: str  # noqa: F841
    status: str  # noqa: F841
    download_filename: str  # noqa: F841
    filesize: int  # noqa: F841
    ...
```

**Comment by jendrikseipp** [comment]
Thanks for the suggestions! I'd use a [whitelist module](https://github.com/jendrikseipp/vulture#whitelists) for this. I don't see a way to bake support for this into Vulture.

**Comment by exhuma** [comment]
Adding to this, I also execute the whitelist as a "sanity check". Using the whitelist as suggested fails on that step because a typed dict does not have those attributes. My workaround is to define a function that is only called when we're **not** running as a main-module:

```python
from myapp import MyTypedDict

def check_typed_dicts():
    MyTypedDict.my_key

if __name__ != "__main__":
    check_typed_dicts()
```

This gives vulture enough info to detect the keys as "used" and the module is also executable.

The downside is that when we're executing the whitelist to check if we don't whitelist invalid stuff, anything inside the `check_typed_dicts` function is *not* included. But considering that this only focuses on typed-dicts it should be acceptable.
