### ISSUE TITLE
Augment output with size of unused functions/variables

### ISSUE THREAD

**Issue by jackric** [jendrikseipp/vulture#60]
When Vulture finds lots of unused variables and functions in a codebase, it would be useful to show the size (as lines/AST contents/etc) of each entity. This allows a developer to prioritize his purging work, i.e. pick the juiciest low hanging fruit first.

**Comment by RJ722** [comment]
Hello @jackric 

vulture currently only reports the beginning of the dead code, so we do not have access to the entire entity per se (the complete class, function, etc). We are however working on source range acquisition.
Thank You for the suggestion!

**Comment by jendrikseipp** [comment]
I think vulture already gives some intuition about the size of the found entities since it prints the type of each entity: 
* classes are usually bigger than functions and properties, and all three typically use multiple lines
* attributes, imports and variables are usually just a single line

I don't think printing more information about the size provides much additional help.

**Comment by jackric** [comment]
@jendrikseipp perhaps you've never run vulture over a significantly sized codebase: I see hundreds of unused functions; I'd like line count per function so that I can sort them.

I'm willing to work on this and make it optional with a command line flag.

**Comment by jendrikseipp** [comment]
Unfortunately, getting the number of lines from an AST node is not easy (the AST probably could access the bytecode though). We are currently working on getting this information in a separate issue https://gitlab.com/coala/GSoC-2017/issues/122 .
